// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: patient_monitoring.proto

package ds.service1;

public final class PatientMonitoring {
  private PatientMonitoring() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ds.service1.RequestMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string patient_id = 1;</code>
     * @return The patientId.
     */
    java.lang.String getPatientId();
    /**
     * <code>string patient_id = 1;</code>
     * @return The bytes for patientId.
     */
    com.google.protobuf.ByteString
        getPatientIdBytes();
  }
  /**
   * Protobuf type {@code ds.service1.RequestMessage}
   */
  public  static final class RequestMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ds.service1.RequestMessage)
      RequestMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RequestMessage.newBuilder() to construct.
    private RequestMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RequestMessage() {
      patientId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RequestMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RequestMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              patientId_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.service1.PatientMonitoring.internal_static_ds_service1_RequestMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.service1.PatientMonitoring.internal_static_ds_service1_RequestMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.service1.PatientMonitoring.RequestMessage.class, ds.service1.PatientMonitoring.RequestMessage.Builder.class);
    }

    public static final int PATIENT_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object patientId_;
    /**
     * <code>string patient_id = 1;</code>
     * @return The patientId.
     */
    public java.lang.String getPatientId() {
      java.lang.Object ref = patientId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        patientId_ = s;
        return s;
      }
    }
    /**
     * <code>string patient_id = 1;</code>
     * @return The bytes for patientId.
     */
    public com.google.protobuf.ByteString
        getPatientIdBytes() {
      java.lang.Object ref = patientId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        patientId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getPatientIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, patientId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getPatientIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, patientId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ds.service1.PatientMonitoring.RequestMessage)) {
        return super.equals(obj);
      }
      ds.service1.PatientMonitoring.RequestMessage other = (ds.service1.PatientMonitoring.RequestMessage) obj;

      if (!getPatientId()
          .equals(other.getPatientId())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PATIENT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getPatientId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ds.service1.PatientMonitoring.RequestMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.service1.PatientMonitoring.RequestMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.service1.PatientMonitoring.RequestMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.service1.PatientMonitoring.RequestMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.service1.PatientMonitoring.RequestMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.service1.PatientMonitoring.RequestMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.service1.PatientMonitoring.RequestMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ds.service1.PatientMonitoring.RequestMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ds.service1.PatientMonitoring.RequestMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ds.service1.PatientMonitoring.RequestMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ds.service1.PatientMonitoring.RequestMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ds.service1.PatientMonitoring.RequestMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ds.service1.PatientMonitoring.RequestMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ds.service1.RequestMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ds.service1.RequestMessage)
        ds.service1.PatientMonitoring.RequestMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ds.service1.PatientMonitoring.internal_static_ds_service1_RequestMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ds.service1.PatientMonitoring.internal_static_ds_service1_RequestMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ds.service1.PatientMonitoring.RequestMessage.class, ds.service1.PatientMonitoring.RequestMessage.Builder.class);
      }

      // Construct using ds.service1.PatientMonitoring.RequestMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        patientId_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ds.service1.PatientMonitoring.internal_static_ds_service1_RequestMessage_descriptor;
      }

      @java.lang.Override
      public ds.service1.PatientMonitoring.RequestMessage getDefaultInstanceForType() {
        return ds.service1.PatientMonitoring.RequestMessage.getDefaultInstance();
      }

      @java.lang.Override
      public ds.service1.PatientMonitoring.RequestMessage build() {
        ds.service1.PatientMonitoring.RequestMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ds.service1.PatientMonitoring.RequestMessage buildPartial() {
        ds.service1.PatientMonitoring.RequestMessage result = new ds.service1.PatientMonitoring.RequestMessage(this);
        result.patientId_ = patientId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ds.service1.PatientMonitoring.RequestMessage) {
          return mergeFrom((ds.service1.PatientMonitoring.RequestMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ds.service1.PatientMonitoring.RequestMessage other) {
        if (other == ds.service1.PatientMonitoring.RequestMessage.getDefaultInstance()) return this;
        if (!other.getPatientId().isEmpty()) {
          patientId_ = other.patientId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ds.service1.PatientMonitoring.RequestMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ds.service1.PatientMonitoring.RequestMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object patientId_ = "";
      /**
       * <code>string patient_id = 1;</code>
       * @return The patientId.
       */
      public java.lang.String getPatientId() {
        java.lang.Object ref = patientId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          patientId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string patient_id = 1;</code>
       * @return The bytes for patientId.
       */
      public com.google.protobuf.ByteString
          getPatientIdBytes() {
        java.lang.Object ref = patientId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          patientId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string patient_id = 1;</code>
       * @param value The patientId to set.
       * @return This builder for chaining.
       */
      public Builder setPatientId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        patientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string patient_id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPatientId() {
        
        patientId_ = getDefaultInstance().getPatientId();
        onChanged();
        return this;
      }
      /**
       * <code>string patient_id = 1;</code>
       * @param value The bytes for patientId to set.
       * @return This builder for chaining.
       */
      public Builder setPatientIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        patientId_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ds.service1.RequestMessage)
    }

    // @@protoc_insertion_point(class_scope:ds.service1.RequestMessage)
    private static final ds.service1.PatientMonitoring.RequestMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ds.service1.PatientMonitoring.RequestMessage();
    }

    public static ds.service1.PatientMonitoring.RequestMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RequestMessage>
        PARSER = new com.google.protobuf.AbstractParser<RequestMessage>() {
      @java.lang.Override
      public RequestMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RequestMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RequestMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RequestMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ds.service1.PatientMonitoring.RequestMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ds.service1.ResponseMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 heart_rate = 1;</code>
     * @return The heartRate.
     */
    int getHeartRate();

    /**
     * <code>string blood_pressure = 2;</code>
     * @return The bloodPressure.
     */
    java.lang.String getBloodPressure();
    /**
     * <code>string blood_pressure = 2;</code>
     * @return The bytes for bloodPressure.
     */
    com.google.protobuf.ByteString
        getBloodPressureBytes();
  }
  /**
   * Protobuf type {@code ds.service1.ResponseMessage}
   */
  public  static final class ResponseMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ds.service1.ResponseMessage)
      ResponseMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ResponseMessage.newBuilder() to construct.
    private ResponseMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResponseMessage() {
      bloodPressure_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ResponseMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ResponseMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              heartRate_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              bloodPressure_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.service1.PatientMonitoring.internal_static_ds_service1_ResponseMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.service1.PatientMonitoring.internal_static_ds_service1_ResponseMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.service1.PatientMonitoring.ResponseMessage.class, ds.service1.PatientMonitoring.ResponseMessage.Builder.class);
    }

    public static final int HEART_RATE_FIELD_NUMBER = 1;
    private int heartRate_;
    /**
     * <code>int32 heart_rate = 1;</code>
     * @return The heartRate.
     */
    public int getHeartRate() {
      return heartRate_;
    }

    public static final int BLOOD_PRESSURE_FIELD_NUMBER = 2;
    private volatile java.lang.Object bloodPressure_;
    /**
     * <code>string blood_pressure = 2;</code>
     * @return The bloodPressure.
     */
    public java.lang.String getBloodPressure() {
      java.lang.Object ref = bloodPressure_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bloodPressure_ = s;
        return s;
      }
    }
    /**
     * <code>string blood_pressure = 2;</code>
     * @return The bytes for bloodPressure.
     */
    public com.google.protobuf.ByteString
        getBloodPressureBytes() {
      java.lang.Object ref = bloodPressure_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bloodPressure_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (heartRate_ != 0) {
        output.writeInt32(1, heartRate_);
      }
      if (!getBloodPressureBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, bloodPressure_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (heartRate_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, heartRate_);
      }
      if (!getBloodPressureBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, bloodPressure_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ds.service1.PatientMonitoring.ResponseMessage)) {
        return super.equals(obj);
      }
      ds.service1.PatientMonitoring.ResponseMessage other = (ds.service1.PatientMonitoring.ResponseMessage) obj;

      if (getHeartRate()
          != other.getHeartRate()) return false;
      if (!getBloodPressure()
          .equals(other.getBloodPressure())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + HEART_RATE_FIELD_NUMBER;
      hash = (53 * hash) + getHeartRate();
      hash = (37 * hash) + BLOOD_PRESSURE_FIELD_NUMBER;
      hash = (53 * hash) + getBloodPressure().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ds.service1.PatientMonitoring.ResponseMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.service1.PatientMonitoring.ResponseMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.service1.PatientMonitoring.ResponseMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.service1.PatientMonitoring.ResponseMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.service1.PatientMonitoring.ResponseMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.service1.PatientMonitoring.ResponseMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.service1.PatientMonitoring.ResponseMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ds.service1.PatientMonitoring.ResponseMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ds.service1.PatientMonitoring.ResponseMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ds.service1.PatientMonitoring.ResponseMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ds.service1.PatientMonitoring.ResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ds.service1.PatientMonitoring.ResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ds.service1.PatientMonitoring.ResponseMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ds.service1.ResponseMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ds.service1.ResponseMessage)
        ds.service1.PatientMonitoring.ResponseMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ds.service1.PatientMonitoring.internal_static_ds_service1_ResponseMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ds.service1.PatientMonitoring.internal_static_ds_service1_ResponseMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ds.service1.PatientMonitoring.ResponseMessage.class, ds.service1.PatientMonitoring.ResponseMessage.Builder.class);
      }

      // Construct using ds.service1.PatientMonitoring.ResponseMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        heartRate_ = 0;

        bloodPressure_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ds.service1.PatientMonitoring.internal_static_ds_service1_ResponseMessage_descriptor;
      }

      @java.lang.Override
      public ds.service1.PatientMonitoring.ResponseMessage getDefaultInstanceForType() {
        return ds.service1.PatientMonitoring.ResponseMessage.getDefaultInstance();
      }

      @java.lang.Override
      public ds.service1.PatientMonitoring.ResponseMessage build() {
        ds.service1.PatientMonitoring.ResponseMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ds.service1.PatientMonitoring.ResponseMessage buildPartial() {
        ds.service1.PatientMonitoring.ResponseMessage result = new ds.service1.PatientMonitoring.ResponseMessage(this);
        result.heartRate_ = heartRate_;
        result.bloodPressure_ = bloodPressure_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ds.service1.PatientMonitoring.ResponseMessage) {
          return mergeFrom((ds.service1.PatientMonitoring.ResponseMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ds.service1.PatientMonitoring.ResponseMessage other) {
        if (other == ds.service1.PatientMonitoring.ResponseMessage.getDefaultInstance()) return this;
        if (other.getHeartRate() != 0) {
          setHeartRate(other.getHeartRate());
        }
        if (!other.getBloodPressure().isEmpty()) {
          bloodPressure_ = other.bloodPressure_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ds.service1.PatientMonitoring.ResponseMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ds.service1.PatientMonitoring.ResponseMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int heartRate_ ;
      /**
       * <code>int32 heart_rate = 1;</code>
       * @return The heartRate.
       */
      public int getHeartRate() {
        return heartRate_;
      }
      /**
       * <code>int32 heart_rate = 1;</code>
       * @param value The heartRate to set.
       * @return This builder for chaining.
       */
      public Builder setHeartRate(int value) {
        
        heartRate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 heart_rate = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeartRate() {
        
        heartRate_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object bloodPressure_ = "";
      /**
       * <code>string blood_pressure = 2;</code>
       * @return The bloodPressure.
       */
      public java.lang.String getBloodPressure() {
        java.lang.Object ref = bloodPressure_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          bloodPressure_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string blood_pressure = 2;</code>
       * @return The bytes for bloodPressure.
       */
      public com.google.protobuf.ByteString
          getBloodPressureBytes() {
        java.lang.Object ref = bloodPressure_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bloodPressure_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string blood_pressure = 2;</code>
       * @param value The bloodPressure to set.
       * @return This builder for chaining.
       */
      public Builder setBloodPressure(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        bloodPressure_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string blood_pressure = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearBloodPressure() {
        
        bloodPressure_ = getDefaultInstance().getBloodPressure();
        onChanged();
        return this;
      }
      /**
       * <code>string blood_pressure = 2;</code>
       * @param value The bytes for bloodPressure to set.
       * @return This builder for chaining.
       */
      public Builder setBloodPressureBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        bloodPressure_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ds.service1.ResponseMessage)
    }

    // @@protoc_insertion_point(class_scope:ds.service1.ResponseMessage)
    private static final ds.service1.PatientMonitoring.ResponseMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ds.service1.PatientMonitoring.ResponseMessage();
    }

    public static ds.service1.PatientMonitoring.ResponseMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResponseMessage>
        PARSER = new com.google.protobuf.AbstractParser<ResponseMessage>() {
      @java.lang.Override
      public ResponseMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResponseMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResponseMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResponseMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ds.service1.PatientMonitoring.ResponseMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AlertRequestMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ds.service1.AlertRequestMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string alert_message = 1;</code>
     * @return The alertMessage.
     */
    java.lang.String getAlertMessage();
    /**
     * <code>string alert_message = 1;</code>
     * @return The bytes for alertMessage.
     */
    com.google.protobuf.ByteString
        getAlertMessageBytes();

    /**
     * <code>string patient_id = 2;</code>
     * @return The patientId.
     */
    java.lang.String getPatientId();
    /**
     * <code>string patient_id = 2;</code>
     * @return The bytes for patientId.
     */
    com.google.protobuf.ByteString
        getPatientIdBytes();
  }
  /**
   * Protobuf type {@code ds.service1.AlertRequestMessage}
   */
  public  static final class AlertRequestMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ds.service1.AlertRequestMessage)
      AlertRequestMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AlertRequestMessage.newBuilder() to construct.
    private AlertRequestMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AlertRequestMessage() {
      alertMessage_ = "";
      patientId_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AlertRequestMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AlertRequestMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              alertMessage_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              patientId_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.service1.PatientMonitoring.internal_static_ds_service1_AlertRequestMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.service1.PatientMonitoring.internal_static_ds_service1_AlertRequestMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.service1.PatientMonitoring.AlertRequestMessage.class, ds.service1.PatientMonitoring.AlertRequestMessage.Builder.class);
    }

    public static final int ALERT_MESSAGE_FIELD_NUMBER = 1;
    private volatile java.lang.Object alertMessage_;
    /**
     * <code>string alert_message = 1;</code>
     * @return The alertMessage.
     */
    public java.lang.String getAlertMessage() {
      java.lang.Object ref = alertMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        alertMessage_ = s;
        return s;
      }
    }
    /**
     * <code>string alert_message = 1;</code>
     * @return The bytes for alertMessage.
     */
    public com.google.protobuf.ByteString
        getAlertMessageBytes() {
      java.lang.Object ref = alertMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        alertMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PATIENT_ID_FIELD_NUMBER = 2;
    private volatile java.lang.Object patientId_;
    /**
     * <code>string patient_id = 2;</code>
     * @return The patientId.
     */
    public java.lang.String getPatientId() {
      java.lang.Object ref = patientId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        patientId_ = s;
        return s;
      }
    }
    /**
     * <code>string patient_id = 2;</code>
     * @return The bytes for patientId.
     */
    public com.google.protobuf.ByteString
        getPatientIdBytes() {
      java.lang.Object ref = patientId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        patientId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAlertMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, alertMessage_);
      }
      if (!getPatientIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, patientId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAlertMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, alertMessage_);
      }
      if (!getPatientIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, patientId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ds.service1.PatientMonitoring.AlertRequestMessage)) {
        return super.equals(obj);
      }
      ds.service1.PatientMonitoring.AlertRequestMessage other = (ds.service1.PatientMonitoring.AlertRequestMessage) obj;

      if (!getAlertMessage()
          .equals(other.getAlertMessage())) return false;
      if (!getPatientId()
          .equals(other.getPatientId())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ALERT_MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getAlertMessage().hashCode();
      hash = (37 * hash) + PATIENT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getPatientId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ds.service1.PatientMonitoring.AlertRequestMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.service1.PatientMonitoring.AlertRequestMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.service1.PatientMonitoring.AlertRequestMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.service1.PatientMonitoring.AlertRequestMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.service1.PatientMonitoring.AlertRequestMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.service1.PatientMonitoring.AlertRequestMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.service1.PatientMonitoring.AlertRequestMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ds.service1.PatientMonitoring.AlertRequestMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ds.service1.PatientMonitoring.AlertRequestMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ds.service1.PatientMonitoring.AlertRequestMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ds.service1.PatientMonitoring.AlertRequestMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ds.service1.PatientMonitoring.AlertRequestMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ds.service1.PatientMonitoring.AlertRequestMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ds.service1.AlertRequestMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ds.service1.AlertRequestMessage)
        ds.service1.PatientMonitoring.AlertRequestMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ds.service1.PatientMonitoring.internal_static_ds_service1_AlertRequestMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ds.service1.PatientMonitoring.internal_static_ds_service1_AlertRequestMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ds.service1.PatientMonitoring.AlertRequestMessage.class, ds.service1.PatientMonitoring.AlertRequestMessage.Builder.class);
      }

      // Construct using ds.service1.PatientMonitoring.AlertRequestMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        alertMessage_ = "";

        patientId_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ds.service1.PatientMonitoring.internal_static_ds_service1_AlertRequestMessage_descriptor;
      }

      @java.lang.Override
      public ds.service1.PatientMonitoring.AlertRequestMessage getDefaultInstanceForType() {
        return ds.service1.PatientMonitoring.AlertRequestMessage.getDefaultInstance();
      }

      @java.lang.Override
      public ds.service1.PatientMonitoring.AlertRequestMessage build() {
        ds.service1.PatientMonitoring.AlertRequestMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ds.service1.PatientMonitoring.AlertRequestMessage buildPartial() {
        ds.service1.PatientMonitoring.AlertRequestMessage result = new ds.service1.PatientMonitoring.AlertRequestMessage(this);
        result.alertMessage_ = alertMessage_;
        result.patientId_ = patientId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ds.service1.PatientMonitoring.AlertRequestMessage) {
          return mergeFrom((ds.service1.PatientMonitoring.AlertRequestMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ds.service1.PatientMonitoring.AlertRequestMessage other) {
        if (other == ds.service1.PatientMonitoring.AlertRequestMessage.getDefaultInstance()) return this;
        if (!other.getAlertMessage().isEmpty()) {
          alertMessage_ = other.alertMessage_;
          onChanged();
        }
        if (!other.getPatientId().isEmpty()) {
          patientId_ = other.patientId_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ds.service1.PatientMonitoring.AlertRequestMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ds.service1.PatientMonitoring.AlertRequestMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object alertMessage_ = "";
      /**
       * <code>string alert_message = 1;</code>
       * @return The alertMessage.
       */
      public java.lang.String getAlertMessage() {
        java.lang.Object ref = alertMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          alertMessage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string alert_message = 1;</code>
       * @return The bytes for alertMessage.
       */
      public com.google.protobuf.ByteString
          getAlertMessageBytes() {
        java.lang.Object ref = alertMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          alertMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string alert_message = 1;</code>
       * @param value The alertMessage to set.
       * @return This builder for chaining.
       */
      public Builder setAlertMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        alertMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string alert_message = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAlertMessage() {
        
        alertMessage_ = getDefaultInstance().getAlertMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string alert_message = 1;</code>
       * @param value The bytes for alertMessage to set.
       * @return This builder for chaining.
       */
      public Builder setAlertMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        alertMessage_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object patientId_ = "";
      /**
       * <code>string patient_id = 2;</code>
       * @return The patientId.
       */
      public java.lang.String getPatientId() {
        java.lang.Object ref = patientId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          patientId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string patient_id = 2;</code>
       * @return The bytes for patientId.
       */
      public com.google.protobuf.ByteString
          getPatientIdBytes() {
        java.lang.Object ref = patientId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          patientId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string patient_id = 2;</code>
       * @param value The patientId to set.
       * @return This builder for chaining.
       */
      public Builder setPatientId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        patientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string patient_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPatientId() {
        
        patientId_ = getDefaultInstance().getPatientId();
        onChanged();
        return this;
      }
      /**
       * <code>string patient_id = 2;</code>
       * @param value The bytes for patientId to set.
       * @return This builder for chaining.
       */
      public Builder setPatientIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        patientId_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ds.service1.AlertRequestMessage)
    }

    // @@protoc_insertion_point(class_scope:ds.service1.AlertRequestMessage)
    private static final ds.service1.PatientMonitoring.AlertRequestMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ds.service1.PatientMonitoring.AlertRequestMessage();
    }

    public static ds.service1.PatientMonitoring.AlertRequestMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AlertRequestMessage>
        PARSER = new com.google.protobuf.AbstractParser<AlertRequestMessage>() {
      @java.lang.Override
      public AlertRequestMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AlertRequestMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AlertRequestMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AlertRequestMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ds.service1.PatientMonitoring.AlertRequestMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AlertResponseMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ds.service1.AlertResponseMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string status_message = 1;</code>
     * @return The statusMessage.
     */
    java.lang.String getStatusMessage();
    /**
     * <code>string status_message = 1;</code>
     * @return The bytes for statusMessage.
     */
    com.google.protobuf.ByteString
        getStatusMessageBytes();
  }
  /**
   * Protobuf type {@code ds.service1.AlertResponseMessage}
   */
  public  static final class AlertResponseMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ds.service1.AlertResponseMessage)
      AlertResponseMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AlertResponseMessage.newBuilder() to construct.
    private AlertResponseMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AlertResponseMessage() {
      statusMessage_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AlertResponseMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AlertResponseMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              statusMessage_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.service1.PatientMonitoring.internal_static_ds_service1_AlertResponseMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.service1.PatientMonitoring.internal_static_ds_service1_AlertResponseMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.service1.PatientMonitoring.AlertResponseMessage.class, ds.service1.PatientMonitoring.AlertResponseMessage.Builder.class);
    }

    public static final int STATUS_MESSAGE_FIELD_NUMBER = 1;
    private volatile java.lang.Object statusMessage_;
    /**
     * <code>string status_message = 1;</code>
     * @return The statusMessage.
     */
    public java.lang.String getStatusMessage() {
      java.lang.Object ref = statusMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        statusMessage_ = s;
        return s;
      }
    }
    /**
     * <code>string status_message = 1;</code>
     * @return The bytes for statusMessage.
     */
    public com.google.protobuf.ByteString
        getStatusMessageBytes() {
      java.lang.Object ref = statusMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        statusMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getStatusMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, statusMessage_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getStatusMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, statusMessage_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ds.service1.PatientMonitoring.AlertResponseMessage)) {
        return super.equals(obj);
      }
      ds.service1.PatientMonitoring.AlertResponseMessage other = (ds.service1.PatientMonitoring.AlertResponseMessage) obj;

      if (!getStatusMessage()
          .equals(other.getStatusMessage())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATUS_MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getStatusMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ds.service1.PatientMonitoring.AlertResponseMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.service1.PatientMonitoring.AlertResponseMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.service1.PatientMonitoring.AlertResponseMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.service1.PatientMonitoring.AlertResponseMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.service1.PatientMonitoring.AlertResponseMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ds.service1.PatientMonitoring.AlertResponseMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ds.service1.PatientMonitoring.AlertResponseMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ds.service1.PatientMonitoring.AlertResponseMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ds.service1.PatientMonitoring.AlertResponseMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ds.service1.PatientMonitoring.AlertResponseMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ds.service1.PatientMonitoring.AlertResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ds.service1.PatientMonitoring.AlertResponseMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ds.service1.PatientMonitoring.AlertResponseMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ds.service1.AlertResponseMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ds.service1.AlertResponseMessage)
        ds.service1.PatientMonitoring.AlertResponseMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ds.service1.PatientMonitoring.internal_static_ds_service1_AlertResponseMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ds.service1.PatientMonitoring.internal_static_ds_service1_AlertResponseMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ds.service1.PatientMonitoring.AlertResponseMessage.class, ds.service1.PatientMonitoring.AlertResponseMessage.Builder.class);
      }

      // Construct using ds.service1.PatientMonitoring.AlertResponseMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        statusMessage_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ds.service1.PatientMonitoring.internal_static_ds_service1_AlertResponseMessage_descriptor;
      }

      @java.lang.Override
      public ds.service1.PatientMonitoring.AlertResponseMessage getDefaultInstanceForType() {
        return ds.service1.PatientMonitoring.AlertResponseMessage.getDefaultInstance();
      }

      @java.lang.Override
      public ds.service1.PatientMonitoring.AlertResponseMessage build() {
        ds.service1.PatientMonitoring.AlertResponseMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ds.service1.PatientMonitoring.AlertResponseMessage buildPartial() {
        ds.service1.PatientMonitoring.AlertResponseMessage result = new ds.service1.PatientMonitoring.AlertResponseMessage(this);
        result.statusMessage_ = statusMessage_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ds.service1.PatientMonitoring.AlertResponseMessage) {
          return mergeFrom((ds.service1.PatientMonitoring.AlertResponseMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ds.service1.PatientMonitoring.AlertResponseMessage other) {
        if (other == ds.service1.PatientMonitoring.AlertResponseMessage.getDefaultInstance()) return this;
        if (!other.getStatusMessage().isEmpty()) {
          statusMessage_ = other.statusMessage_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ds.service1.PatientMonitoring.AlertResponseMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ds.service1.PatientMonitoring.AlertResponseMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object statusMessage_ = "";
      /**
       * <code>string status_message = 1;</code>
       * @return The statusMessage.
       */
      public java.lang.String getStatusMessage() {
        java.lang.Object ref = statusMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          statusMessage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string status_message = 1;</code>
       * @return The bytes for statusMessage.
       */
      public com.google.protobuf.ByteString
          getStatusMessageBytes() {
        java.lang.Object ref = statusMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          statusMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string status_message = 1;</code>
       * @param value The statusMessage to set.
       * @return This builder for chaining.
       */
      public Builder setStatusMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        statusMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string status_message = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatusMessage() {
        
        statusMessage_ = getDefaultInstance().getStatusMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string status_message = 1;</code>
       * @param value The bytes for statusMessage to set.
       * @return This builder for chaining.
       */
      public Builder setStatusMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        statusMessage_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ds.service1.AlertResponseMessage)
    }

    // @@protoc_insertion_point(class_scope:ds.service1.AlertResponseMessage)
    private static final ds.service1.PatientMonitoring.AlertResponseMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ds.service1.PatientMonitoring.AlertResponseMessage();
    }

    public static ds.service1.PatientMonitoring.AlertResponseMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AlertResponseMessage>
        PARSER = new com.google.protobuf.AbstractParser<AlertResponseMessage>() {
      @java.lang.Override
      public AlertResponseMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AlertResponseMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AlertResponseMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AlertResponseMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ds.service1.PatientMonitoring.AlertResponseMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ds_service1_RequestMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ds_service1_RequestMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ds_service1_ResponseMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ds_service1_ResponseMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ds_service1_AlertRequestMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ds_service1_AlertRequestMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ds_service1_AlertResponseMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ds_service1_AlertResponseMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030patient_monitoring.proto\022\013ds.service1\"" +
      "$\n\016RequestMessage\022\022\n\npatient_id\030\001 \001(\t\"=\n" +
      "\017ResponseMessage\022\022\n\nheart_rate\030\001 \001(\005\022\026\n\016" +
      "blood_pressure\030\002 \001(\t\"@\n\023AlertRequestMess" +
      "age\022\025\n\ralert_message\030\001 \001(\t\022\022\n\npatient_id" +
      "\030\002 \001(\t\".\n\024AlertResponseMessage\022\026\n\016status" +
      "_message\030\001 \001(\t2\275\001\n\030PatientMonitoringServ" +
      "ice\022N\n\021MonitorVitalSigns\022\033.ds.service1.R" +
      "equestMessage\032\034.ds.service1.ResponseMess" +
      "age\022Q\n\nAlertNurse\022 .ds.service1.AlertReq" +
      "uestMessage\032!.ds.service1.AlertResponseM" +
      "essageb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ds_service1_RequestMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ds_service1_RequestMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ds_service1_RequestMessage_descriptor,
        new java.lang.String[] { "PatientId", });
    internal_static_ds_service1_ResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ds_service1_ResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ds_service1_ResponseMessage_descriptor,
        new java.lang.String[] { "HeartRate", "BloodPressure", });
    internal_static_ds_service1_AlertRequestMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ds_service1_AlertRequestMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ds_service1_AlertRequestMessage_descriptor,
        new java.lang.String[] { "AlertMessage", "PatientId", });
    internal_static_ds_service1_AlertResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ds_service1_AlertResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ds_service1_AlertResponseMessage_descriptor,
        new java.lang.String[] { "StatusMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
